<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>xyz.juandiii</groupId>
    <artifactId>ark-quarkus-jackson-vertx-parent</artifactId>
    <version>1.0.8-SNAPSHOT</version>
  </parent>
  <artifactId>ark-quarkus-jackson-vertx</artifactId>
  <name>ark-quarkus-jackson-vertx - Runtime</name>
  <description>Quarkus extension runtime for Ark Vert.x Mutiny transport (add-on on top of ark-quarkus-jackson)</description>
  <url>https://github.com/juandiii/ark</url>

  <licenses>
    <license>
      <name>Apache License, Version 2.0</name>
      <url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>
      <distribution>repo</distribution>
    </license>
  </licenses>
  <developers>
    <developer>
      <name>Juan Diego</name>
      <url>https://github.com/juandiii</url>
    </developer>
  </developers>

  <scm>
    <connection>scm:git:git://github.com/juandiii/ark.git</connection>
    <developerConnection>scm:git:ssh://github.com:juandiii/ark.git</developerConnection>
    <url>https://github.com/juandiii/ark</url>
  </scm>

  <dependencies>
    <dependency>
      <groupId>xyz.juandiii</groupId>
      <artifactId>ark-quarkus-jackson</artifactId>
      <version>${project.version}</version>
    </dependency>

    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-vertx</artifactId>
    </dependency>

    <dependency>
      <groupId>xyz.juandiii</groupId>
      <artifactId>ark-mutiny</artifactId>
      <version>${project.version}</version>
    </dependency>

    <dependency>
      <groupId>xyz.juandiii</groupId>
      <artifactId>ark-transport-vertx-mutiny</artifactId>
      <version>${project.version}</version>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>io.quarkus</groupId>
        <artifactId>quarkus-extension-maven-plugin</artifactId>
        <version>${quarkus.version}</version>
        <extensions>true</extensions>
        <executions>
          <execution>
            <phase>compile</phase>
            <goals>
              <goal>extension-descriptor</goal>
            </goals>
            <configuration>
              <deployment>${project.groupId}:ark-quarkus-jackson-vertx-deployment:${project.version}</deployment>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
          <annotationProcessorPaths>
            <path>
              <groupId>io.quarkus</groupId>
              <artifactId>quarkus-extension-processor</artifactId>
              <version>${quarkus.version}</version>
            </path>
          </annotationProcessorPaths>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
